sonar.projectKey=Quiz-Api
sonar.projectName=Quiz Api
sonar.host.url=http://localhost:9000

sonar.sources=src
sonar.tests=test

sonar.exclusions=node_modules/**,dist/**,coverage/**

sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info